### ISSUE TITLE
Problems with the sell status after buying a claim

### ISSUE THREAD

**Issue by Cqmmls** [Xyness/SimpleClaimSystem#1]
If I buy a claim sold by another player, and the claim does appear in my claim list after the purchase is successful with Shift + Left, but the purchased territory is still on sale, is this normal, was it originally designed to be like this? Or should it be better to set the status of the territory that the buyer is buying to a closed state?

**Comment by Xyness** [comment]
Hey ! I’ll check and fix it asap ! Thank’s for your report

**Comment by Xyness** [comment]
@Cqmmls Hey i just fixed the issue, thank you for your report
