### ISSUE TITLE
Autofly Issue in Spectator Mode

### ISSUE THREAD

**Issue by RobyWood** [Xyness/SimpleClaimSystem#13]
Hello, I have a problem.
When a player has autofly enabled and switches to spectator / creative mode, if they leave their claim, they fall into the void :/

**Comment by Xyness** [comment]
Hi, its fixed on the 1.11.6

**Comment by RobyWood** [comment]
Thx, do you know roughly when she’s coming out?

**Comment by Xyness** [comment]
Its available

**Comment by RobyWood** [comment]
Yes, I hadn’t noticed, however the problem is still there :/

**Comment by Xyness** [comment]
Its fixed normally :) try on 1.11.6.1 update
