### ISSUE TITLE
Auto Purge removing claims instantly

### ISSUE THREAD

**Issue by EasyMochi** [Xyness/SimpleClaimSystem#3]
Hello, when typing 12w in the auto purge setting, when someone disconnects after creating a few claims it purges them as soon as the check runs.

Also, your discord link is down~

If you need more info let me know!

**Comment by Xyness** [comment]
Hey, yes i will update the discord link, you can use this one for the moment : https://discord.gg/Z8Md688c

For the auto-purge issue, for what parameter did you put 12w.

Thank’s for reporting btw

**Comment by EasyMochi** [comment]
Thanks for the lightning fast reply!

The parameter that was changed was this one:

`auto-purge-time-without-login: 12w`

Steps to repro:

1. Change to `auto-purge-time-without-login: 12w`
2. Have someone (Not OP so far) create multiple claims
3. Have that someone log off
