### ISSUE TITLE
Documentation clarity

### ISSUE THREAD

**Issue by EasyMochi** [Xyness/SimpleClaimSystem#4]
The documentation is quite confusing when it comes to status-settings and default-values-settings.

I am unsure whether for example "Explosions" means whether or not a visitor is able to trigger an explosion, or a creeper, or if it's just about the block damage for the explosions.

Same goes for "Damages", it isn't clear what it is. It would be nice to have a little description of all of those status-settings so we know what we are doing! Thanks.

**Comment by Xyness** [comment]
Hey, i just updated the documentation, hope it will be more comprehensible now.

https://xyness.gitbook.io/simpleclaimsystem/configuration/claim-settings

Thank's!
